account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import my_profile_view, invites_received_view, ProfileLIstView, invite_profiles_list_view, send_invitation, \
    remove_from_friends, accept_invitation, reject_invitation, invite_profiles_list_views, friends_list,\
    people_you_mayKnow, invites_received_view2, ProfileDetailView, user_search

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', views.dashboard, name='dashboard'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('register/', views.register, name='register'),
    path('myprofile/', my_profile_view, name='my-profile-view'),
    path('my-invites2/', invites_received_view2, name='my-invites-view2'),
    path('my-invites/', invites_received_view, name='my-invites-view'),
    path('all-profiles/', ProfileLIstView.as_view(), name='all-profiles-view'),
    path('to-invite/', invite_profiles_list_view, name='invite-profiles-view'),
    path('to-invites/', invite_profiles_list_views, name='invite-profiles-views'),
    path('send-invite/', send_invitation, name='send-invite'),
    path('remove-friend/', remove_from_friends, name='remove-friend'),
    path('my-invites/accept', accept_invitation, name='accept-invite'),
    path('my-invites/reject', reject_invitation, name='reject-invite'),
    path('friends', friends_list, name='friends'),
    path('peopleyoumayknow', people_you_mayKnow, name='peopleyoumayknow'),
    path('search', user_search, name='search'),
    path('<slug>/', ProfileDetailView.as_view(), name='profile-details'),

]

chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.index, name='index'),
]

posts/urls.py
from django.urls import path
from .views import post_comment_create_and_list_view, like_unlike_post, PostDeleteView, PostUpdateView

app_name = 'posts'

urlpatterns = [
    path('', post_comment_create_and_list_view, name='main-post-view'),
    path('liked/', like_unlike_post, name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),

]

visible/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('chat/', include('chat.urls', namespace='chat')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

account/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.db.models import Q
from .utils import get_random_code
from django.shortcuts import reverse
from cloudinary.models import CloudinaryField
# Create your models here.


class ProfileManager(models.Manager):
    def get_all_profiles_to_invite(self, sender):
        profiles = Profile.objects.all().exclude(user=sender)
        profile = Profile.objects.get(user=sender)
        qs = Relationship.objects.filter(Q(sender=profile) | Q(receiver=profile))
        print(qs)
        accepted = set([])
        for rel in qs:
            if rel.status == 'accepted':
                accepted.add(rel.receiver)
                accepted.add(rel.sender)
        print(accepted)

        available = [profile for profile in profiles if profile not in accepted]
        print(available)
        return available

    def get_all_profiles(self, me):
        profiles = Profile.objects.all().exclude(user=me)
        return profiles


class Profile(models.Model):
    first_name = models.CharField(max_length=200, blank=True)
    last_name = models.CharField(max_length=200, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(default='no bio...', max_length=300)
    email = models.EmailField(max_length=200, blank=True)
    gender = models.CharField(max_length=10, blank=True)
    date_of_birth = models.DateField(blank=True, null=True)
    city = models.CharField(max_length=30, default='Lagos', blank=True)
    country = models.CharField(max_length=200, blank=True)
    avatar = CloudinaryField('avatar', default='avatar.png', )
    friends = models.ManyToManyField(User, blank=True, related_name='friends')
    work_place = models.CharField(blank=True, max_length=400)
    school = models.CharField(blank=True, max_length=300)
    slug = models.SlugField(unique=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = ProfileManager()

    def __str__(self):
        return f"{self.user.username}-{self.created.strftime('%d-%m-%y')}"

    def get_absolute_url(self):
        return reverse("profile-details", kwargs={"slug": self.slug})

    def get_friends(self):
        return self.friends.all()

    def get_friends_no(self):
        return self.friends.all().count()

    def get_post_no(self):
        return self.posts.all().count()

    def get_all_authors_post(self):
        return self.posts.all()

    def get_likes_given_no(self):
        likes = self.like_set.all()
        total_liked = 0
        for item in likes:
            if item.value == 'Like':
                total_liked += 1
        return total_liked

    def get_likes_received_no(self):
        posts = self.posts.all()
        total_liked = 0
        for item in posts:
            total_liked += item.liked.all().count()
        return total_liked

    __initial_first_name = None
    __initial_last_name = None
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__initial_first_name = self.first_name
        self.__initial_last_name = self.last_name

    def save(self, *args, **kwargs):
        ex = False
        to_slug = self.slug
        if self.first_name != self.__initial_first_name or self.last_name != self.__initial_last_name or self.slug =="":
            if self.first_name and self.last_name:
                to_slug = slugify(str(self.first_name) + '' + str(self.last_name))
                ex = Profile.objects.filter(slug=to_slug).exists()
                while ex:
                    to_slug = slugify(to_slug + '' + str(get_random_code()))
                    ex = Profile.objects.filter(slug=to_slug).exists()
            else:
                to_slug = str(self.user)
        self.slug = to_slug
        super().save(*args, **kwargs)


STATUS_CHOICES = (
    ('sender', 'send'),
    ('accepted', 'accepted')
)


class RelationshipManager(models.Manager):
    def invitations_received(self, receiver):
        qs = Relationship.objects.filter(receiver=receiver, status='send')
        return qs


class Relationship(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='receiver')
    status = models.CharField(max_length=8, choices=STATUS_CHOICES)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = RelationshipManager()

    def __str__(self):
        return f"{self.sender}-{self.receiver}-{self.status}"

account/forms.py
from django import forms
from .models import Profile


class ProfileModelForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'bio', 'avatar', 'city', 'country', 'gender', 'school', 'work_place', 'date_of_birth')


class SearchForm(forms.Form):
    query = forms.CharField()

account/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.postgres.search import SearchVector
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.db.models import Q
from .models import Profile, Relationship
from .forms import ProfileModelForm, SearchForm
from django.views.generic import ListView, DetailView


@login_required
def dashboard(request):
    return render(request, 'account/dashboard.html', {'section': 'dashboard'})


def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        # first_name = request.POST['first_name']
        # last_name = request.POST['last_name']
        email = request.POST['email']
        password = request.POST['password']
        password_repeat = request.POST['password_repeat']

        if password == password_repeat:
            if User.objects.filter(username=username).exists():
                messages.info(request, 'username already taken')
                return render(request, 'account/register.html')
            elif User.objects.filter(email=email).exists():
                messages.info(request, 'Email already exist')
                return render(request, 'account/register.html')
            else:
                user = User.objects.create_user(username=username, email=email, password=password)
                user.save()
               # Profile.objects.create(user=user)

                return render(request, 'account/register_done.html')

        else:
            messages.info(request, 'Passwords did not match.')
            return render(request, 'account/register.html')

    else:
        return render(request, 'account/register.html')


class ProfileDetailView(DetailView):
    model = Profile
    template_name = 'account/detail.html'

    def get_object(self, slug=None):
        slug = self.kwargs.get('slug')
        profile = Profile.objects.get(slug=slug)
        return profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user.username)
        profile = Profile.objects.get(user=user)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)
        context['rel_receiver'] = rel_receiver
        context['rel_sender'] = rel_sender
        context['posts'] = self.get_object().get_all_authors_post()
        context['len_post'] = True if len(self.get_object().get_all_authors_post()) > 0 else False

        return context

def my_profile_view(request):
    profile = Profile.objects.get(user=request.user)
    form = ProfileModelForm(request.POST or None, request.FILES or None, instance=profile)
    confirm = False

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            confirm = True

    context = {
        'profile': profile,
        'form': form,
        'confirm': confirm,
    }
    return render(request, 'profile.html', context)


def invites_received_view(request):
    profile = Profile.objects.get(user=request.user)
    qs = Relationship.objects.invitations_received(profile)
    results = list(map(lambda x: x.sender, qs))
    is_empty = False
    if len(results) == 0:
        is_empty = True

    context = {'qs': results,
               'is_empty': is_empty, }

    print(results)
    print('-----------')
    print(qs)
    return render(request, 'profiles/my_invites.html', context)


def invites_received_view2(request):
    profile = Profile.objects.get(user=request.user)
    qs = Relationship.objects.invitations_received(profile)
    results = list(map(lambda x: x.sender, qs))
    is_empty = False
    if len(results) == 0:
        is_empty = True

    context = {'qs': results,
               'is_empty': is_empty, }

   # print(results)
    #print('-----------')
   # print(qs)
    return render(request, 'profiles/my_invites2.html', context)


def accept_invitation(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        if rel.status == 'send':
            rel.status = 'accepted'
            rel.save()
    return redirect('my-invites-view')


def reject_invitation(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        receiver = Profile.objects.get(user=request.user)
        sender = Profile.objects.get(pk=pk)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        rel.delete()
    return redirect('my-invites-view')


def invite_profiles_list_view(request):
    user = request.user
    qs = Profile.objects.get_all_profiles_to_invite(user)

    context = {'qs': qs}

    return render(request, 'profiles/to_invite_list.html', context)


def invite_profiles_list_views(request):
    user = request.user
    ap = Profile.objects.get_all_profiles_to_invite(user)

    context = {'ap': ap}

    return render(request, 'profiles/to_invite_list1.html', context)


def profiles_list_view(request):
    user = request.user
    qs = Profile.objects.get_all_profiles(user)

    context = {'qs': qs}

    return render(request, 'profiles/profile_list.html', context)


class ProfileLIstView(ListView):
    model = Profile
    template_name = 'profiles/profile_list.html'

    context_object_name = 'qs'

    def get_queryset(self):
        qs = Profile.objects.get_all_profiles(self.request.user)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=str(self.request.user))
        profile = Profile.objects.get(user=user)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)
        context['rel_receiver'] = rel_receiver
        context['rel_sender'] = rel_sender
        context['is_empty'] = False
        if len(self.get_queryset()) == 0:
            context['is_empty'] = True

        return context


def send_invitation(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        rel = Relationship.objects.create(sender=sender, receiver=receiver, status='send')
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('my-profile-view')


def remove_from_friends(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        rel = Relationship.objects.get((Q(sender=sender)
                                        & Q(receiver=receiver)) | Q(sender=receiver) & Q(receiver=sender))
        rel.delete()
        return redirect(request.META.get('HTTP_REFERER'))

    return redirect('my-profile-view')


def friends_list(request):
    user = request.user
    profile = Profile.objects.get(user=user)
    qs = Profile.get_friends(user)
    print(qs)
    context = {
        'qs': qs,
    }

    return render(request, 'profiles/friend_lists.html', context)


def people_you_mayKnow(request):
    profile = Profile.objects.get(user=request.user)
    people = Profile.objects.all()
    user = request.user
    people_you_mayknow = Profile.objects.get_all_profiles_to_invite(user)

    context = {
        'people': people_you_mayknow,
    }
    print(people_you_mayknow)
    print(profile)
    return render(request, 'profiles/peopple-you-may-know.html', context)


def user_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Profile.objects.annotate(search=SearchVector('first_name', 'last_name', 'user'),).filter(search=query)
    return render(request, 'profiles/search.html', {'form': form, 'query': query, 'results': results})

account/templates/base.html
  {% load static %}
{% load cloudinary %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <!--Custom css -->
      <link rel="stylesheet" type="text/css" href={% static 'style.css' %}>
      <link rel="stylesheet" type="text/css" href={% static 'style2.css' %}>
    <!-- semantic UI -->
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>


    <title>Visible {% block title %}{% endblock title %}</title>
{#  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">#}

  </head>

  <body>

  {% include 'navbar.html' %}

    <div class="ui container">
      {% block content %}

      {% endblock content %}
    </div>




{#{% include 'footer.html' %}#}
</body>
{% block scripts %}

     <script>
            $(document).ready(function (){
        $('#modal-btn').click(function (){
            $('.ui.longer.modal')
            .modal('show');
        })

    })
</script>
{% endblock scripts %}

 <!--Custom js ADD HERE-->
  <script type="text/javascript" src="{% static 'main.js' %}"></script>

</html>

account/templates/footer.html
<!--footer-->
{% load static %}
      <link rel="stylesheet" type="text/css" href={% static 'style2.css' %}>
          <link rel="stylesheet" type="text/css" href={% static 'style4.css' %}>
{#  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">#}

    <!-- semantic UI -->

{#<footer>#}
{#<div class="container-fluid padding footer ">#}
{#  <div class="row text-center footer-color">#}
{#    <div class="col-md-4 footer-color ">#}
{#      <a href="index.html"> VISIBLE</a>#}
{#      <hr class="light">#}
{#      <p>+(234)-811-256-3962 info@visible.com</p>#}
{#      <p>312 Herbert Marcauley Way Sabo Yaba, </p>#}
{#      <P>Lagos Nigeria</P>#}
{#    </div>#}
{#    <div class="col-md-4 footer-color">#}
{#      <hr class="light">#}
{#      <h5>Products</h5>#}
{#      <hr class="light">#}
{#      <p>VISICloud</p>#}
{#      <p>Visible developers</p>#}
{#      <p>Viscoin</p>#}
{##}
{#    </div>#}
{#    <div class="col-md-4 footer-color">#}
{#      <hr class="light">#}
{#      <h5>Data Centers </h5>#}
{#      <hr class="light">#}
{#      <p>Ibom plaza Uyo</p>#}
{#      <p>Nyere Audioruim University of Dare salem</p>#}
{#      <p>Rivers</p>#}
{##}
{#    </div>#}
{#    <div class="col-12 footer-color" >#}
{#      <hr class="light-last">#}
{#      <p class="foot-note"> © <script>var CurrentYear = new Date().getFullYear()#}
{#        document.write(CurrentYear)</script> Visible | Built with Love by Group 9</p>#}
{#    </div>#}
{#  </div>#}
{#</div>#}
{##}
{#</footer>#}

{#<div class="ui inverted vertical footer segment">#}
{#    <div class="ui center aligned container">#}
{#      <div class="ui stackable inverted divided grid">#}
{#        <div class="three wide column">#}
{#          <h4 class="ui inverted header">VISIBLE</h4>#}
{#          <div class="ui inverted link list">#}
{#           <p>+(234)-811-256-3962 info@visible.com</p>#}
{#         <p>312 Herbert Marcauley Way Sabo Yaba, </p>#}
{#         <P>Lagos Nigeria</P>#}
{#          </div>#}
{#        </div>#}
{#        <div class="three wide column">#}
{#          <h4 class="ui inverted header">Products</h4>#}
{#          <div class="ui inverted link list">#}
{#            <p>VISICloud</p>#}
{#        <p>Visible developers</p>#}
{#         <p>Viscoin</p>#}
{#          </div>#}
{#        </div>#}
{#        <div class="three wide column">#}
{#          <h4 class="ui inverted header">Data Centers</h4>#}
{#          <div class="ui inverted link list">#}
{#            <p>Ibom plaza Uyo</p>#}
{#      <p>Nyere Audioruim University of Dare salem</p>#}
{#      <p>Rivers Centers PH</p>#}
{#          </div>#}
{#        </div>#}
{#        <div class="seven wide column">#}
{#          <h4 class="ui inverted header">Visible</h4>#}
{#          <p>Connecting you to all your friends.</p>#}
{#        </div>#}
{#      </div>#}
{#      <div class="ui inverted section divider"></div>#}
{#     <p class="foot-note"> © <script>var CurrentYear = new Date().getFullYear()#}
{#      document.write(CurrentYear)</script> Visible | Built with Love by Group 9</p>#}
{#      <div class="ui horizontal inverted small divided link list">#}
{#        <a class="item" href="#">Site Map</a>#}
{#        <a class="item" href="#">Contact Us</a>#}
{#        <a class="item" href="#">Terms and Conditions</a>#}
{#        <a class="item" href="#">Privacy Policy</a>#}
{#      </div>#}
{#    </div>#}
{#</div>#}

{#<div class="ui inverted vertical footer segment">#}
{#    <div class="ui center aligned container">#}
{#      <div class="ui stackable inverted divided grid">#}
{#        <div class="three wide column">#}
{#          <h4 class="ui inverted header">VISIBLE</h4>#}
{#          <div class="ui inverted link list">#}
{#           <p>+(234)-811-256-3962 info@visible.com</p>#}
{#         <p>312 Herbert Marcauley Way Sabo Yaba, </p>#}
{#         <P>Lagos Nigeria</P>#}
{#          </div>#}
{#        </div>#}
{#        <div class="three wide column">#}
{#          <h4 class="ui inverted header">Products</h4>#}
{#          <div class="ui inverted link list">#}
{#            <p>VISICloud</p>#}
{#        <p>Visible developers</p>#}
{#         <p>Viscoin</p>#}
{#          </div>#}
{#        </div>#}
{#        <div class="three wide column">#}
{#          <h4 class="ui inverted header">Data Centers</h4>#}
{#          <div class="ui inverted link list">#}
{#            <p>Ibom plaza Uyo</p>#}
{#      <p>Nyere Audioruim University of Dare salem</p>#}
{#      <p>Rivers Centers PH</p>#}
{#          </div>#}
{#        </div>#}
{#        <div class="seven wide column">#}
{#          <h4 class="ui inverted header">Visible</h4>#}
{#          <p>Connecting you to all your friends.</p>#}
{#        </div>#}
{#      </div>#}
{#      <div class="ui inverted section divider"></div>#}
{#     <p class="foot-note"> © <script>var CurrentYear = new Date().getFullYear()#}
{#      document.write(CurrentYear)</script> Visible | Built with Love by Group 9</p>#}
{#      <div class="ui horizontal inverted small divided link list">#}
{#        <a class="item" href="#">Site Map</a>#}
{#        <a class="item" href="#">Contact Us</a>#}
{#        <a class="item" href="#">Terms and Conditions</a>#}
{#        <a class="item" href="#">Privacy Policy</a>#}
{#      </div>#}
{#    </div>#}
{#</div>#}

account/templates/navbar.html
{% load static %}



<div class="ui inverted navsemantic  menu">
    <a href="" class="item">
      <a href="{% url 'posts:main-post-view' %}"> <h2 > Visible</h2> </a>
    </a>
    {% if request.user.is_authenticated %}
          <a class="active item" href="{% url 'posts:main-post-view' %}">
            Home
          </a>
     {% endif %}
          <a class="item" href="{% url 'my-profile-view' %}">
            My Profile
          </a>
            <a class="item" href="{% url 'friends' %}">
            Friends
          </a>

          <a class="item" href="{% url 'all-profiles-view' %}">
            People
          </a>

            <a class="item" href="{% url 'my-invites-view' %}">
            Friend Requests
          </a>



          <div class="right menu">
               {% if request.user.is_authenticated %}

{#                    {% if query %}#}
{#                        <h1>Posts containing "{{ query }}"</h1>#}
{#                        <h3>#}
{#                        {% with results.count as total_results %}#}
{#                        Found {{ total_results }} result{{ total_results|pluralize }}#}
{#                        {% endwith %}#}
{#                        </h3>#}
{#                        {% for user in results %}#}
{#                        <h4><a href="{{ user.avatar.url }}">{{ user.first_name }} {{ user.last_name }}</a></h4>#}
{#                        {{ user.body }}#}
{#                        {% empty %}#}
{#                        <p>There are no results for your query.</p>#}
{#                        {% endfor %}#}
{#                        <p><a href="{% url "search" %}">Search again</a></p>#}
{#                        {% else %}#}
{#                        <h1>Search for posts</h1>#}
{#                        <form method="get">#}
{#                        {{ form.as_p }}#}
{#                        <input type="submit" value="Search">#}
{#                        </form>#}
{#                        {% endif %}#}
{#            <div class="item">#}
{#              <div class="ui icon input">#}
{#                 #}
{#                <input type="text" placeholder="Search...">#}
{#                <i class="search link icon"></i>#}
{#              </div>#}
{#            </div>#}
                <p class="ui item"> Hello {{ request.user }}</p>
            <a class="ui item" href="{% url "logout" %}">
              Logout
            </a>
                    {% else %}
                   <a href="{% url 'login' %}" class="ui item">
                Login
            </a>
              {% endif %}
          </div>
</div>














{#  <nav class=" nav navbar navbar-expand-md navbar-inverse bg-dark sticky-top">#}
{#    <div class="container-fluid">#}
{#      <a class="logo nabar-brand navbrand1"   href="{% url 'posts:main-post-view' %}">VISIBLE</a><p class="pa"></p>#}
{#      <button class="custom-toggler navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">#}
{#        <span class="navbar-toggler-icon"></span>#}
{#      </button>#}
{#      <div class="collapse navbar-collapse" id="navbarResponsive">#}
{#        <ul class="navbar-nav ml-auto">#}
{#          <li {% if section == "dashboard" %}class="selected"{% endif %} class=" link nav-item active">#}
{#            <a class=" navlink nav-link" href="{% url "dashboard" %}"><strong>Home</strong><span class="sr-only">(current)</span></a>#}
{#          </li>#}
{#          <li {% if section == "images" %}class="selected"{% endif %} class="nav-item">#}
{#            <a class=" navlink nav-link" href="{% url 'my-profile-view' %}"><strong>Profile</strong></a>#}
{#          </li>#}
{#          <li {% if section == "people" %}class="selected"{% endif %} class=" nav-item">#}
{#            <a class=" navlink nav-link" href="{% url 'all-profiles-view' %}"><strong>People</strong></a>#}
{#          </li>#}
{##}
{##}
{#        </ul>#}
{#       {% endif %}#}
{#        <span class="user">#}
{#        {% if request.user.is_authenticated %}#}
{#        Hello {{ request.user }},#}
{#        <a class="login" href="{% url "logout" %}">Logout</a>#}
{#        {% else %}#}
{#        <a class="login" href="{% url "login" %}">Login</a>#}
{#            <a class="login" href="">Register</a>#}
{#        {% endif %}#}
{#        </span>#}
{#      </div>#}
{#    </div>#}
{#  </nav>#}









{% if messages %}
<ul class="messages">
{% for message in messages %}
<li class="{{ message.tags }}">
{{ message|safe }}
<a href="#" class="close">x</a>
</li>
{% endfor %}
</ul>
{% endif %}